// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnpsDwPuIDMMyW5C18-e6hbizco2Qxfc',
    appId: '1:121174944945:web:d31bc20f80d8463e11c690',
    messagingSenderId: '121174944945',
    projectId: 'petshop-754cb',
    authDomain: 'petshop-754cb.firebaseapp.com',
    storageBucket: 'petshop-754cb.appspot.com',
    measurementId: 'G-CQW3Y48RZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZt4kdImcXZVLBu2Og2MzijMHi4mCj92o',
    appId: '1:121174944945:android:ff14c554424b8ecb11c690',
    messagingSenderId: '121174944945',
    projectId: 'petshop-754cb',
    storageBucket: 'petshop-754cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tbjRBflMBa_Uq11RC6b_9QMEaEkg6Z8',
    appId: '1:121174944945:ios:a9cfc0efbb42483211c690',
    messagingSenderId: '121174944945',
    projectId: 'petshop-754cb',
    storageBucket: 'petshop-754cb.appspot.com',
    iosBundleId: 'com.prak.pet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tbjRBflMBa_Uq11RC6b_9QMEaEkg6Z8',
    appId: '1:121174944945:ios:239aecb57d18149f11c690',
    messagingSenderId: '121174944945',
    projectId: 'petshop-754cb',
    storageBucket: 'petshop-754cb.appspot.com',
    iosBundleId: 'com.prak.pet.RunnerTests',
  );
}
